myapp:
  build: .
  ports:
    - "8000:8000"
  environment:
    PORT: "8000"
    PGHOST: db
    AWS_ACCESS_KEY_ID : "ACCESS KEY HERE"
    AWS_SECRET_ACCESS_KEY : "SECRET ACCESS KEY HERE"
  links:
    - db

db:
  build: ./postgres/
  ports:
    - "5432:5432"
  environment:
    PGDATA: /data/pgdata
    POSTGRES_PASSWORD: PASSWORD_HERE
    POSTGRES_USER: postgres
  volumes:
    - ./postgres/data:/data/pgdata


