myapp:
  build: .
  ports:
    - "8000:8000"
  environment:
    PORT: "8000"
    PGHOST: db
  links:
    - db

db:
  build: ./postgres/
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: GCTORSTORAGEMASTER
    POSTGRES_USER: postgres