myapp:
  build: .
  ports:
    - "8010:8000"
  environment:
    PORT: "8000"
    PGHOST: db
  links:
    - db

db:
  build: ./postgres/
  environment:
    POSTGRES_PASSWORD: GCTORSTORAGEMASTER
    POSTGRES_USER: postgres

